pipeline {
    agent any

    triggers {
        githubPush()
    }

    stages {

        stage('Checkout') {
            steps {
                git url: 'https://github.com/Rareshs/simple-java-maven-app.git',
                    branch: 'master',
                    credentialsId: 'github_cred'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }
    }

    post {
        success {
            echo "Build + Test succeeded!"
            archiveArtifacts artifacts: 'target/*.jar', fingerprint: true

            build job: 'Test_Pipeline_Credentials',
                  propagate: false
        }
        failure {
            echo "Build failed!"
        }
    }
}
